{{- if .Values.bff.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "discrete-layer-client.fullname" . }}-bff
  labels:
    app: {{ template "discrete-layer-client.name" . }}
    component: bff-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    collectord.io/index: {{ quote .Values.splunkIndex }}    
spec:
  replicas: {{ .Values.bff.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "discrete-layer-client.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-bff
  template:
    metadata:
      labels:
        app: {{ template "discrete-layer-client.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-bff
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecretName }} 
      containers:    
        - name: {{ .Chart.Name }}-bff
          image: "{{ .Values.bff.image }}:{{ .Values.bff.imageTag}}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bff.env.SERVER_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs/api
              port: {{ .Values.bff.env.SERVER_PORT }}
            initialDelaySeconds: 30
            timeoutSeconds: 1
          {{- if .Values.bff.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.bff.resources.requests.memory }}
              cpu: {{ .Values.bff.resources.requests.cpu }}
            limits:
              memory: {{ .Values.bff.resources.limits.memory }}
              cpu: {{ .Values.bff.resources.limits.cpu }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "discrete-layer-client.fullname" . }}-bff-configmap
          volumeMounts:
            - name: production-json
              mountPath: /usr/src/app/config/production.json
              subPath: production.json
      volumes:
        - name: production-json
          configMap:
            name: {{ template "discrete-layer-client.fullname" . }}-bff-configmap
            items:
              - key: "production.json"
                path: "production.json"
{{- end }}
