{{- if .Values.bff.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discrete-layer-client.fullname" . }}-bff-configmap
  labels:
    app: {{ template "discrete-layer-client.name" . }}
    component: bff-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  OPENAPI_FILE_PATH: {{ quote .Values.bff.env.OPENAPI_FILE_PATH }}
  LOG_LEVEL: {{ quote .Values.bff.env.LOG_LEVEL }}
  SERVER_PORT: {{ quote .Values.bff.env.SERVER_PORT }}
  REQUEST_PAYLOAD_LIMIT: {{ quote .Values.bff.env.REQUEST_PAYLOAD_LIMIT }}
  RESPONSE_COMPRESSION_ENABLED: {{ quote .Values.bff.env.RESPONSE_COMPRESSION_ENABLED }}
  CSW_RASTER_URL: {{ quote .Values.bff.env.CSW_RASTER_URL }}
  CSW_3D_URL: {{ quote .Values.bff.env.CSW_3D_URL }}
  CSW_DEM_URL: {{ quote .Values.bff.env.CSW_DEM_URL }}
  MAP_SERVICE_RASTER_URL: {{ quote .Values.bff.env.MAP_SERVICE_RASTER_URL }}
  CATALOG_SERVICE_RASTER_URL: {{ quote .Values.bff.env.CATALOG_SERVICE_RASTER_URL }}
  CATALOG_SERVICE_3D_URL: {{ quote .Values.bff.env.CATALOG_SERVICE_3D_URL }}
  CATALOG_SERVICE_DEM_URL: {{ quote .Values.bff.env.CATALOG_SERVICE_DEM_URL }}
  INGESTION_SERVICE_RASTER_URL: {{ quote .Values.bff.env.INGESTION_SERVICE_RASTER_URL }}
  INGESTION_SERVICE_3D_URL: {{ quote .Values.bff.env.INGESTION_SERVICE_3D_URL }}
  INGESTION_SERVICE_DEM_URL: {{ quote .Values.bff.env.INGESTION_SERVICE_DEM_URL }}
  JOB_SERVICE_COMMON_URL: {{ quote .Values.bff.env.JOB_SERVICE_COMMON_URL }}
  SERVED_ENTITY_TYPES: {{ quote .Values.globalClientApp.env.SERVED_ENTITY_TYPES }}
  STORAGE_EXPLORER_RASTER_URL: {{ quote .Values.bff.env.STORAGE_EXPLORER_RASTER_URL }}
  STORAGE_EXPLORER_3D_URL: {{ quote .Values.bff.env.STORAGE_EXPLORER_3D_URL }}
  LOOKUP_TABLES_SERVICE_URL: {{ quote .Values.bff.env.LOOKUP_TABLES_SERVICE_URL }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_ATTRIBUTE_NAME }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_INJECTION_TYPE }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_TOKEN_VALUE }}
  SERVICE_DISCOVERY_URL: {{ quote .Values.bff.env.SERVICE_DISCOVERY_URL }}
  PYCSW-RECORD_RASTER-URL: {{ quote .Values.bff.env.PYCSW_RECORD_RASTER_URL }}
  PYCSW-RECORD_3D-URL: {{ quote .Values.bff.env.PYCSW_RECORD_3D_URL }}
  PYCSW-RECORD_DEM-URL: {{ quote .Values.bff.env.PYCSW_RECORD_DEM_URL }}
  MAP_SERVER-RECORD_RASTER-URL: {{ quote .Values.bff.env.MAP_SERVER_RECORD_RASTER_URL }}
  WFS_URL: {{ quote .Values.bff.env.WFS_URL }}
  WFS_SERVICES_CONFIG: {{ quote .Values.bff.env.WFS_SERVICES_CONFIG }}
  EXPORT_LAYER_RASTER_URL: {{  quote .Values.bff.env.EXPORT_LAYER_RASTER_URL }}
  EXPORT_LAYER_3D_URL: {{  quote .Values.bff.env.EXPORT_LAYER_3D_URL }}
  EXPORT_LAYER_DEM_URL: {{  quote .Values.bff.env.EXPORT_LAYER_DEM_URL }}
  production.json: {{ .Files.Get "config/production.json" | quote }}
{{- end }}
