{{- if .Values.discreteClient.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "discrete-layer-client.fullname" . }}-ui
  labels:
    app: {{ template "discrete-layer-client.name" . }}
    component: discrete-layer-client-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # In case cloudProvider=azure
  {{- if eq .Values.cloudProvider "azure" }}
  type: ClusterIP
  {{- end }}
  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.discreteClient.SERVICE_PORT }}
      targetPort: 8080 # DO NOT CHANGE, AS IT'S HARDCODED IN APPLICATION.
      protocol: TCP
      name: http
      {{- if eq .Values.cloudProvider "minikube" }}
      nodePort: {{ .Values.discreteClient.NODE_PORT }}
      {{- end }}
  selector:
    app: {{ template "discrete-layer-client.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-ui
{{- end }}
