{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if eq .Values.ingress.type "nginx-kubernetes" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- if eq .Values.ingress.type "nginx-org" }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: 'ServiceName={{ template "discrete-layer-client.fullname" . }}-ui rewrite=/;ServiceName={{ template "discrete-layer-client.fullname" . }}-bff rewrite=/;ServiceName={{ template "discrete-layer-client.fullname" . }}-tools rewrite=/'
    {{- end }}
    #nginx.org/redirect-to-https: "True" #dont work in minion, should be set in master
    #nginx.org/hsts-behind-proxy: "True" #dont work in minion or master despite documentation
  name: {{ template "discrete-layer-client.fullname" . }}-ingress
spec:
  rules:
    - host: {{quote .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "discrete-layer-client.fullname" . }}-ui
                port:
                  number: {{ .Values.discreteClient.SERVICE_PORT }}
            path: {{ .Values.ingress.ui.externalPath }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
            pathType: Prefix
          - backend:
              service:
                name: {{ template "discrete-layer-client.fullname" . }}-bff
                port:
                  number: {{ .Values.bff.SERVICE_PORT }}
            path: {{ .Values.ingress.bff.externalPath }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
            pathType: Prefix
          - backend:
              service:
                name: {{ template "discrete-layer-client.fullname" . }}-tools
                port:
                  number: {{ .Values.tools.SERVICE_PORT }}
            path: {{ .Values.ingress.tools.externalPath }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
            pathType: Prefix
{{- end }}
