{{- if and .Values.caSecret.name (and .Values.caSecret.key .Values.caSecret.value) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caSecret.name }}
type: Opaque
data:
  {{ .Values.caSecret.key }}: {{ .Values.caSecret.value | b64enc | quote }}
{{- end -}}