{{- if .Values.tools.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discrete-layer-client.fullname" . }}-tools-configmap
  labels:
    app: {{ template "discrete-layer-client.name" . }}
    component: tools-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  CONFIGURATION_IMAGE_TAG: {{ quote .Values.tools.imageTag }}
  CONFIGURATION_PUBLIC_URL: {{ quote .Values.tools.env.PUBLIC_URL }}
  CONFIGURATION_MAP_CENTER: {{ quote .Values.tools.env.MAP.CENTER }}
  CONFIGURATION_MAP_ZOOM: {{ quote .Values.tools.env.MAP.ZOOM }}
  CONFIGURATION_BASE_MAPS: {{ quote .Values.tools.env.BASE_MAPS }}
  CONFIGURATION_DEFAULT_TERRAIN_PROVIDER_URL: {{ quote .Values.tools.env.DEFAULT_TERRAIN_PROVIDER_URL }}
  CONFIGURATION_APPS: {{ quote .Values.tools.env.APPS }}
{{- end }}
